version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1f27
      - POSTGRES_DB=postgres
    volumes:
      - ../todo-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  postgres:
